# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surame')),
                ('eMail', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('dateTimeVertified', models.DateTimeField(blank=True, null=True)),
                ('dateTimeSent', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Offer from client'), (2, 'Verified'), (3, 'Done'), (4, 'Not verified'), (5, 'Troubles')], max_length=100)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Good')),
            ],
        ),
    ]
