# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20170306_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='uploads/images')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Bookmap')),
            ],
        ),
    ]
