# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.ImageField(default='test', upload_to='uploads/images'),
        ),
    ]
