# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20170309_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmap',
            name='map',
            field=models.ImageField(default='test', upload_to='uploads/maps'),
        ),
    ]
