# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_bookmap_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Bookmap')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Bookmap')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Bookmap')),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Hero'),
        ),
        migrations.AddField(
            model_name='point',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Place'),
        ),
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Time'),
        ),
    ]
