# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20170312_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
