# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20170404_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='book',
        ),
        migrations.AlterField(
            model_name='point',
            name='place',
            field=models.CharField(max_length=50, verbose_name='Place'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
