# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20170407_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together=set([('name', 'book')]),
        ),
    ]
