# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20170407_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
