# Generated by Django 2.0.3 on 2018-03-29 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('page', '0015_point_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connexion', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of last connexion')),
                ('permissions', models.IntegerField(default=0, verbose_name='Seniority')),
            ],
        ),
    ]
